SELECT * FROM customer.customers;

use customer;

# 1, What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender;

# 2, Which customers used a discountr but still spent more than the average purchase amount ?
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customers
  );

# 3, Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;

# 4, Campare the average Purchase amount between Standard and express Shipping  
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

# 5, Do subscribed customers spend more ? Compare Average spend and total revenue between  subscribers and non-subscribers

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;
          
          
          
# 6, which 5 products have the highest percentage of purchase of purchase with discounts applied?

SELECT 
    item_purchased,
    ROUND(
        SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*) * 100,
        2
    ) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# 7, Segment Customer into New , Returning, and loyal based on their total number of previous purchase,  and show the count of each segment.

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customers
)

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY customer_segment;

# 8, what are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

# 9, Are customers who repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

# 10, what is the revenue contribution  of each age group?

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;